const growUp = [
  {"headImg":"assets/image/headImg.png",
  "name":"lili",
  "time":"2020-02-05 22:00",
  "video":"assets/video/test.mp4",
  "img":"assets/image/class2.png,assets/image/class1.png,assets/image/class2.png,assets/image/class1.png",
  "content":"今天课程十分有意思，我掌握了许多新知识，比如。。。",
  },
  {"headImg":"assets/image/class1.png",
  "img":"assets/image/class2.png,assets/image/class1.png,assets/image/class2.png,assets/image/class1.png",
  "name":"lili",
  "time":"2020-02-05 22:00",
  "video":"assets/video/test.mp4",
  "content":"今天课程十分有意思，我掌握了许多新知识，比如。。。",
  },
];
