List comment = [{
  "commentId":1234,
  "name":"莉莉妈妈",
  "star":4,
  "content":"老师认真负责，孩子说课堂十分有趣，自己收货颇多，希望能有效提高孩子成绩。",
  "date":"2018-10-10",
  "headImg":"assets/image/headImg.png",
  "commentImg":"assets/icon/comment.png,assets/icon/comment.png,assets/icon/comment.png,assets/icon/comment.png,assets/icon/comment.png,assets/icon/comment.png,assets/icon/comment.png",
},
{
  "commentId":1235,
  "name":"莉妈妈",
  "star":5,
  "content":"老师认真负责，孩子说课堂十分有趣，自己收货颇多，希望能有效提高孩子成绩。",
  "date":"2018-10-10",
  "headImg":"assets/image/headImg.png",
  "commentImg":"assets/icon/comment.png,assets/icon/comment.png",
},
{
  "commentId":1236,
  "name":"莉妈妈2",
  "star":3,
  "content":"老师认真负责，孩子说课堂十分有趣，自己收货颇多，希望能有效提高孩子成绩。",
  "date":"2018-10-10",
  "headImg":"assets/image/headImg.png",
  "commentImg":"",
}
];
