name: educationapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_redux: ^0.6.0
  dio: ^3.0.7
  shared_preferences: ^0.5.6+1
  image_picker: ^0.6.3+1
  fluttertoast: ^3.1.3
  video_player: ^0.10.8+1
  json_serializable: ^3.2.5
  chewie: ^0.9.8+1
  image_gallery_saver: ^1.2.2
  path_provider: ^1.6.1
  build_runner: ^1.7.4
  json_annotation: ^3.0.1
  provider: ^4.0.4
  multi_image_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icon/home.png
   - assets/icon/home-active.png
   - assets/icon/message.png
   - assets/icon/message-active.png
   - assets/icon/shopcart-unactive.png
   - assets/icon/shopcart-active.png
   - assets/icon/book.png
   - assets/icon/book-active.png
   - assets/icon/myCenter.png
   - assets/icon/myCenter-active.png
   - assets/icon/arrow-left-black.png
   - assets/icon/eye-close.png
   - assets/icon/eye-open.png
   - assets/icon/QQ.png
   - assets/icon/wechat.png
   - assets/image/welcome.png
   - assets/image/headImg.png
   - assets/icon/menu-attend.png
   - assets/icon/menu-class.png
   - assets/icon/menu-homework.png
   - assets/icon/menu-collect.png
   - assets/icon/menu-reading.png
   - assets/icon/menu-remark.png
   - assets/icon/menu-result.png
   - assets/image/banner.png
   - assets/image/blank.png
   - assets/icon/title-bar.png
   - assets/icon/arrow-right-blue.png
   - assets/icon/icon-setup.png
   - assets/icon/search.png
   - assets/icon/icon-xunzhang.png
   - assets/icon/arrow-right-white.png
   - assets/icon/circle-bg.png
   - assets/icon/arrow-right-black.png
   - assets/icon/center-attend.png
   - assets/icon/center-class.png
   - assets/icon/center-grow.png
   - assets/icon/center-message.png
   - assets/icon/center-remark.png
   - assets/icon/arrow-left-white.png
   - assets/icon/back-exit.png
   - assets/icon/icon-white-back.png
   - assets/icon/icon-white-share.png
   - assets/icon/icon-dark-back.png
   - assets/icon/icon-dark-share.png
   - assets/icon/icon-location.png
   - assets/icon/icon-star-unactive.png
   - assets/icon/icon-star-active.png
   - assets/icon/unfocus-on.png
   - assets/icon/focus-on.png
   - assets/icon/circle-cancel.png
   - assets/icon/collection.png
   - assets/icon/comment.png
   - assets/icon/icon-head.png
   - assets/icon/icon-ticket.png
   - assets/icon/arrow-right-grey.png
   - assets/icon/radio-uncheck.png
   - assets/icon/radio-check.png
   - assets/icon/wechat-pay.png
   - assets/icon/card-pay.png
   - assets/icon/zfb-pay.png
   - assets/icon/balance-pay.png
   - assets/icon/icon-female.png
   - assets/image/card-bg.png
   - assets/icon/icon-male.png
   - assets/icon/course-search.png
   - assets/icon/switch-layout.png
   - assets/icon/arrow-left-grey.png
   - assets/icon/collect-more.png
   - assets/icon/collect-search.png
   - assets/icon/switch-row.png
   - assets/icon/collect-unselect.png
   - assets/icon/collect-select.png
   - assets/icon/icon-dustbin.png
   - assets/icon/collection-heart.png
   - assets/icon/homework-check.png
   - assets/icon/homework-uncheck.png
   - assets/icon/icon-none.png
   - assets/icon/camera.png
   - assets/icon/video.png
   - assets/icon/icon-create.png
   - assets/icon/homework-wait.png
   - assets/icon/homework-success.png
   - assets/icon/homework-grade.png
   - assets/video/test.mp4
   - assets/icon/commentStar-active.png
   - assets/icon/commentStar-unactive.png
   - assets/icon/timetable-circle.png
   - assets/icon/ask-for-leave.png
   - assets/icon/has-class.png
   - assets/icon/arrive-class.png
   - assets/icon/wait-for-check.png
   - assets/icon/qingjia.png
   - assets/icon/out-of-class.png
   - assets/icon/empty-cart.png
   - assets/icon/collection-empty.png
   - assets/icon/pay-success.png
   - assets/icon/user-head.png
   

   

   
   
   

   
   
   

   
   





   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
