const classList = [
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'startTime':'8:00','endTime':'8:45',
    'date':'2020-2-16',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'date':'2020-2-16',
    'startTime':'8:50','endTime':'9:35',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class2.png',
    'startTime':'8:00','endTime':'8:45',
    'date':'2020-2-11',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class2.png',
    'date':'2020-2-11',
    'startTime':'8:50','endTime':'9:35',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'date':'2020-2-11',
    'startTime':'9:40','endTime':'10:25',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'date':'2020-2-11',
    'startTime':'10:30','endTime':'11:15'
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'date':'2020-2-17',
    'startTime':'9:40','endTime':'10:25',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class1.png',
    'date':'2020-2-17',
    'startTime':'10:30','endTime':'11:15'
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class2.png',
    'date':'2020-2-19',
    'startTime':'9:40','endTime':'10:25',
  },
  {
    'courseName': '美术趣味课堂',
    'courseHours': '48',
    'courseTeacher': '李老师',
    'courseImg':'assets/image/class2.png',
    'date':'2020-2-19',
    'startTime':'10:30','endTime':'11:15'
  },
];
