import 'package:flutter/material.dart';
import 'dart:ui';

const bgColor = Color.fromRGBO(247, 248, 255, 1);
const themeColor = Color.fromRGBO(37, 102, 177, 1);
const loadingColor = Color.fromRGBO(37, 102, 177, 0.3);
double width = MediaQueryData.fromWindow(window).size.width;
double height = MediaQueryData.fromWindow(window).size.height;
double topPadding = MediaQueryData.fromWindow(window).padding.top;
const borderColor = Color.fromRGBO(247, 248, 255, 1);
const redColor = Color.fromRGBO(255, 62, 48, 1);
const lightGrey = Color.fromRGBO(158, 158, 163, 1);
BorderRadius baseRadius = BorderRadius.circular(5.0);
const baseFontSize = 14.0;
const sFontSize = 12.0;
const titleSize = 18.0;
const mFontSize = 16.0;
const secondFontColor = Color.fromRGBO(191, 191, 191, 1);
const baseFontColor = Color.fromRGBO(49, 50, 56, 1);
TextStyle baseFontStyle = TextStyle(color: baseFontColor, fontSize: baseFontSize);
